### PR TITLE
Update for iOS 8

### PR DESCRIPTION
**Pull request by tateu**
I have no way to test this on iOS 5, 6 or 7 but it works on iOS 8.4

### CODE REVIEW

**Comment by k3a** [comment]
Thanks for the commit, I will test it in a week on iOS7 and lower, potentially make some changes to make it work and release it. I will mention you in the description.

**Comment by tateu** [comment]
I've since updated to this (the reasons why are listed in the commit notes): https://github.com/tateu/AutoBrightness/commit/3e94b1ae858b905ab7d19af9cb22c0cb6bef0e34

and there is also BKSDisplayBrightnessSetAutoBrightnessEnabled, if you want to disable iOS Auto-Brightness.

I also noticed that there was atleast one official release (with a flipSwitch) that is newer than the source code posted here.

**Comment by tateu** [comment]
And some more changes: https://github.com/tateu/AutoBrightness/commits/master

Specifically a settings panel to allow the user to customize intervals and other options.

https://imgur.com/eaj2ZL4

https://github.com/tateu/AutoBrightness/commit/9d887b3afb77d348af58bdb61da9331539bdf19f

**Comment by k3a** [comment]
I am getting this on iOS7. Any idea what to try to fix it?

backboardd[30]: HID: The 'Rate Controlled' connection 'ambid' access to protected services is denied.

**Comment by tateu** [comment]
That shouldn't be there.

#define useBackBoardServices (kCFCoreFoundationVersionNumber >= 1140.10) //iOS8

should keep all of the new backboardd methods from running on iOS versions prior to iOS8 and it should run just like it did previously.

The only two possibilities I see:

1) I missed something and my checks for if (useBackBoardServices) don't catch everything that they should. I just went back over the code and I'm not seeing anything that I missed.

2) In order to use the backboardd methods on iOS8, I had to add an entitlements file for "com.apple.backboard.displaybrightness." I didn't think it would matter but that entitlement file is compiled in for all iOS versions. Maybe it is causing problems on older versions?

**Comment by k3a** [comment]
Hehe, it works on iOS6 and iOS8.
So that problem is only on iOS7.1.2 (the only 7 I own). It is using the
old method (tested). and I have no idea how to fix it. :/ Maybe we just
ignore that...

I tried to compile settings but got some nasty compilation errors.
That's not your fault but my screwed headers. I hate how often apple
changes stuff. So it looks like you will have it to compile the final
.deb to include the settings.

**Comment by k3a** [comment]
... the new method on that iOS7.1.2 doesn't work either, logs the same error. Searching on google showed that more people saw that error message on ios7 for different software. Maybe some bug in iOS or some cool security feature which was removed in ios8? Who knows...

**Comment by tateu** [comment]
You could always just split off and release an iOS 8 only version, AutoBrightness8 or some such. I'm starting to do that when I have major changes to my tweaks.

Sure, I can compile any versions you need.

**Comment by k3a** [comment]
Hmm, you could release AutoBrightness8 yourself and eventually make
future updates but what if some people installed AutoBrightness on ios8
and they won't know about that update.. so maybe better to update
AutoBrightness. The current cydia AutoBrightness doesn't work on iOS7
either - tested.

So please compile the deb and make pull request so we have github in sync.

You can put some credits in Settings if you want. If I update
AutoBrightness package I will definitely mention you in the update
description, just let me know how to mention you (possible with some URL
if you want). Without you there wouldn't be an update as I can't do
tweak development actively anymore due to multiple reasons..

Thanks

**Comment by tateu** [comment]
Do you have the source code for the FlipSwitch, so I can include it?

**Comment by k3a** [comment]
You mean the SBSettings toggle?
It is part of the source:
https://github.com/k3a/AutoBrightness/tree/master/autobrightnesssbsettingstoggle

My local repo doesn't have any useful uncommitted/unpushed changes.

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

```
.theos/
_/
autobrightnesssbsettingstoggle/obj/
flipswitchtoggle/
me.k3a.ab_1.1.0-1_iphoneos-arm.deb
obj/
```

$ git push
Everything up-to-date

**Comment by tateu** [comment]
http://cydiaupdates.net/pkg/me.k3a.ab
http://moreinfo.thebigboss.org/moreinfo/depiction.php?file=autobrightnessDp

Says the newest release was on 01/10/2014 05:04 PM and
In this version:
- iOS7 / arm64 support
- FlipSwitch/FlipControlCenter switch

but the github source was last updated on Aug 24, 2013

**Comment by k3a** [comment]
Ah yep, missed the "flipswitchtoggle" in the untracked files list.
I pushed it into my git
https://github.com/k3a/AutoBrightness/tree/master/flipswitchtoggle .

Mention about iOS7 is probably not correct. I don't know, it's quite a
long time since I released that update, maybe it worked that time but it
doesn't on my iPhone 4 @ 7.1.2 and 7.1.2 is the latest for that device.
So maybe it worked in previous 7.x versions but doesn't in the latest...

**Comment by tateu** [comment]
I'm pretty sure I was using it on iOS 7.x on my 5s. It was a long time ago, I can't be sure, though.

Ok, I should be able to get to this tonight, in the next 10 hours or so. I'll update with the FlipSwitch toggle, compile and submit a pull request.

**Comment by k3a** [comment]
Cool, thanks

**Pull request merged**
