### PR TITLE
Some changes, fixes and an update for iOS 9.

### PR DESCRIPTION
**Pull request by tateu**

### CODE REVIEW

**Comment by k3a** [comment]
I can't get it to compile still :(

Getting problems like "sys/cdefs.h:655:2: error: Unsupported architecture", probably caused by new compiler because similar problems are with iOS 7.1 SDK.

Can you again please compile the deb so I can update it in BigBoss repo? Thanks.

**Comment by tateu** [comment]
It's already there: https://github.com/k3a/AutoBrightness/blob/master/me.k3a.ab_1.3.0-1_iphoneos-arm.deb

**Comment by k3a** [comment]
Submitted, thanks!

**Comment by tateu** [comment]
Do you have any idea why com.ericasadun.utilities is getting added to the control file as a dependency on Bigboss? It has been there since v1.1.0-1, 2014/10/01, even though it's not in the package I built. It looks like a mistake or a leftover from an older version that is no longer needed.

Depends: firmware (>= 5.0), com.ericasadun.utilities, preferenceloader

**Comment by k3a** [comment]
Originally it was used in postinst to disable iOS system autobrightness.
This is no longer happening and I don't see this dependency in
DEBIAN/control. So I think it was kept there by BigBoss manager. I will
write to him to remove this depedency.

**Pull request merged**
